### ISSUE TITLE
Anyway to refresh the environment?

### ISSUE THREAD

**Issue by matthewmueller** [cloudflare/tableflip#15]
This is a bit of a stretch, but is it possible to somehow refresh the environment in between `SIGHUP`s? It seems like you'd need to pass a config file in, but I'm wondering if there's some magic to potentially refresh `os.Environ()` in between reloads.

For context, I'm looking to setup something like heroku where you have `heroku config:set key value`, that would restart the app with a new environment, but it doesn't seem like there's anyway to do that without some special programming from the binary itself (e.g. load from this file)

**Comment by lmb** [comment]
I don't think the OS provides a way to change the environ of a running process (see https://stackoverflow.com/questions/205064/). Are you unable to change the program for some reason?

**Comment by matthewmueller** [comment]
I think you're right about that too. 

My main use case was just trying to change the program via environment variables without passing in a config file, but it makes sense why nginx and others use a config file now.

Thanks!
