### ISSUE TITLE
supervisord

### ISSUE THREAD

**Issue by zhiqiangxu** [cloudflare/tableflip#18]
supervisord requires non-daemonized processes, is there a way to work out?

**Comment by lmb** [comment]
I'm not familiar with `supervisord`, but have you looked at http://supervisord.org/subprocess.html#pidproxy-program ?

**Comment by zhiqiangxu** [comment]
> I'm not familiar with `supervisord`, but have you looked at http://supervisord.org/subprocess.html#pidproxy-program ?

Looks promising, will try it out !

**Comment by lmb** [comment]
Any luck? Can I close this issue?

**Comment by lmb** [comment]
Let me know if you want to revisit this topic.
