### ISSUE TITLE
[Question] Windows

### ISSUE THREAD

**Issue by Belphemur** [cloudflare/tableflip#21]
Hello,

Do you know if the lib would work on Windows ? with GOOS=windows ?

**Comment by lmb** [comment]
Hi!

I've not tested it, but I'm pretty sure it won't work unfortunately. The library relies on the fact that file descriptors follow a predicable pattern on Unix-ish systems. AFAIK Windows uses opaque HANDLEs instead, which means some other method would have to be found.

Do you have a service that needs to work on Unix and Windows, or just Windows?

**Comment by Belphemur** [comment]
Hello Lorenz, 

Thank you for the the quick answer. Thats also what I gathered when I dig into the code, just wanted to be sure. 

It's for a service that currently runs on both OSes, dnscrypt-proxy. I loved the idea of a simple signal to have a new process been run instead of implementing a whole reload logic.

On another note would the lib support sustemd socket? 

Do you think that would be easy or interesting to add? 

________________________________

**Comment by lmb** [comment]
Are you referring to socket activation? I sketched out a solution in https://github.com/cloudflare/tableflip/issues/14#issuecomment-451939430 which might be what you are looking for. Depending on how complex the code ends up being it could become an example, or a sub package.

If socket activation is what you want I'd suggest re-opening that issue.

**Comment by Belphemur** [comment]
Good point.

I'm closing this issue since the answer is "Not working with Windows".

Maybe you could add that somewhere in the readme or have a check for GOOS in the code to fail on compile :)
