### ISSUE TITLE
Logs go missing after systemd-journald restart

### ISSUE THREAD

**Issue by lmb** [cloudflare/tableflip#38]
There is an unfortunate interaction between `tableflip` upgrades and restarting `journald`, see https://github.com/systemd/systemd/issues/13708

The work around is to log to /run/systemd/journald/socket using SOCK_DGRAM. We should document this.

**Comment by fastest963** [comment]
Would the recommendation be to use the `journal`[1] package to log to instead of stdout? 

[1] https://godoc.org/github.com/coreos/go-systemd/journal

**Comment by lmb** [comment]
I've not used that package myself, but it seems to do the correct thing to make this work. You can combine it with https://www.freedesktop.org/software/systemd/man/systemd.exec.html#$JOURNAL_STREAM to only log to journald when being run under systemd.
