### ISSUE TITLE
How to integrate with systemd and supervisor?

### ISSUE THREAD

**Issue by vibyird** [cloudflare/tableflip#39]
Tableflip resolve the graceful process restart problem. However, how to integrate with systemd and supervisor?

**Comment by mozillazg** [comment]
There are some documents about that:

* systemd: https://github.com/cloudflare/tableflip/blob/master/doc.go#L13-L31
* supervisor: http://supervisord.org/subprocess.html#pidproxy-program

**Comment by lmb** [comment]
That's exactly right. Please let me know if those don't help.
