### ISSUE TITLE
Impossible to build for windows

### ISSUE THREAD

**Issue by scraly** [cloudflare/tableflip#40]
Hi,

In an application I use cloudflare/tableflip lib.

I've got an issue when I try to build for windows/386:

```

# github.com/cloudflare/tableflip
../../../../go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/env.go:13:2: cannot use syscall.CloseOnExec (type func(syscall.Handle)) as type func(int) in field value
../../../../go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/fds.go:344:36: not enough arguments in call to syscall.Syscall
../../../../go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/fds.go:344:37: undefined: syscall.SYS_FCNTL
../../../../go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/fds.go:344:60: undefined: syscall.F_DUPFD_CLOEXEC
```

Thanks

**Comment by Zenithar** [comment]
Different types between unix and windows syscalls (https://golang.org/src/syscall/exec_unix.go#L103) and (https://golang.org/src/syscall/exec_windows.go#L124)

**Comment by lmb** [comment]
Hi, `tableflip` doesn't work on Windows I'm afraid. I've also not tried to port it, so I don't know how much effort it would be.
