### ISSUE TITLE
Not working with systemd as per docs

### ISSUE THREAD

**Issue by mvrhov** [cloudflare/tableflip#6]
Ubuntu Xenial (16.04) is the OS of choice, the command run is `service <name> restart`. The systemd stops and starts the process on restart.

```
[Service]
User=www-data
Group=www-data
Type=simple
Restart=on-failure
RestartSec=5s
RuntimeDirectory=MA
ExecStart=/path/to/executable serve --port=4001 --pid-file=/var/run/MA/foo.pid
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/var/run/MA/foo.pid
```

After the trial and error the only way to do seamples upgrade is to also add `ExecReload=/bin/kill -HUP $MAINPID` and then issue `service <name> reload`.

**Comment by lmb** [comment]
Yes, that's a great point. I didn't add this in the first place because ppl might use something other than signals to ask for an upgrade, but that makes this needlessly hard.

**Comment by lmb** [comment]
Please have a look at the PR and let me know if you think it's appropriate.
